kind: Service
apiVersion: v1
metadata:
  name: hyper-test
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: hyper-test
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http